services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    container_name: navelite-dynamo
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
    volumes:
      - ./.dynamo-data:/home/dynamodblocal/data

  localstack:
    image: localstack/localstack:3.8
    container_name: navelite-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=0
